# Generated by Django 3.0.7 on 2020-06-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200628_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='imaage', upload_to=''),
            preserve_default=False,
        ),
    ]
