# Generated by Django 3.0.7 on 2020-06-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a test description fddhfjjj fhfghjjf'),
            preserve_default=False,
        ),
    ]
